import { StyleSheet } from 'react-native';
import { authColors } from '../theme/authTheme';

const AuthStyles = StyleSheet.create({
  headerContainer: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 18,
    paddingTop: 6,
  },
  topRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 14,
  },
  navRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  logoBackground: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    backgroundColor: '#fff',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: authColors.surfaceBorder,
    shadowColor: authColors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
  },
  logoText: {
    fontWeight: '800',
    color: authColors.primary,
    letterSpacing: -1,
  },
  brandTagline: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '600',
    color: authColors.primary,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  title: {
    fontWeight: '800',
    color: authColors.text,
    marginBottom: 6,
    textAlign: 'center',
  },
  subtitle: {
    color: authColors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 4,
  },
  formContainer: {
    width: '100%',
    marginBottom: 4,
  },
  formDivider: {
    height: 1,
    backgroundColor: authColors.border,
    opacity: 0.65,
    marginVertical: 18,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: authColors.inputBg,
    borderRadius: 16,
    paddingHorizontal: 14,
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: authColors.border,
    minHeight: 54,
  },
  inputContainerFocused: {
    borderColor: authColors.borderFocus,
    backgroundColor: '#fff',
    shadowColor: authColors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    minHeight: 50,
    fontSize: 16,
    color: authColors.text,
  },
  forgotPassword: {
    textAlign: 'right',
    color: authColors.primary,
    fontWeight: '600',
    fontSize: 14,
    marginBottom: 18,
    marginTop: -4,
  },
  signupContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    gap: 4,
  },
  signupText: {
    fontSize: 15,
    color: authColors.textMuted,
  },
  signupLink: {
    fontSize: 15,
    color: authColors.primary,
    fontWeight: '800',
  },
  contentContainer: {
    flexGrow: 1,
  },
  errorText: {
    color: authColors.error,
    marginTop: -8,
    marginBottom: 10,
    fontSize: 13,
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingRight: 8,
    marginLeft: -4,
  },
  backLabel: {
    marginLeft: 2,
    fontSize: 15,
    fontWeight: '600',
    color: authColors.textMuted,
  },
});

export default AuthStyles;
